const $=id=>document.getElementById(id);let token=localStorage.getItem("northcity_admin_token")||"",rules=[],majors=[],middles=[],id=null,orig=null,filter="all";
const f={major:$("major"),middle:$("middle"),type:$("type"),category:$("category"),title:$("title"),summary:$("summary"),content:$("content"),details:$("details"),collapsed:$("collapsed"),note:$("note"),published:$("published"),keywords:$("keywords"),slug:$("slug")};
const api=(p,o={})=>{const h=new Headers(o.headers||{});h.set("x-admin-token",token);if(o.body)h.set("content-type","application/json");return fetch(p,{...o,headers:h,cache:"no-store"})};
const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
const stat=r=>r?.retired_at?"retired":r?.is_published?"published":"draft",label=s=>({published:"公開中",draft:"下書き",retired:"廃止済み"}[s]||"下書き");
function options(){f.major.innerHTML='<option value="">未分類</option>'+majors.map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join("");middleOptions()}
function middleOptions(){const v=f.middle.value,m=+f.major.value;f.middle.innerHTML='<option value="">未分類</option>'+middles.filter(x=>!m||+x.major_id===m).map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join("");if([...f.middle.options].some(o=>o.value===v))f.middle.value=v}
function renderRules(){const q=$("search").value.toLowerCase(),box=$("ruleList");box.innerHTML="";rules.filter(r=>(filter==="all"||stat(r)===filter)&&[r.title,r.summary,r.major_title,r.middle_title,r.keywords].join(" ").toLowerCase().includes(q)).forEach(r=>{const d=document.createElement("div"),s=stat(r);d.className="rule"+(+r.id===+id?" active":"");d.innerHTML=`<button><b>${esc(r.title)}</b><small>${esc([r.major_title,r.middle_title].filter(Boolean).join(" ＞ ")||"未分類")}</small></button><span class="state ${s}">${label(s)}</span>`;d.querySelector("button").onclick=()=>load(r);box.appendChild(d)})}
function statusUI(r){const s=stat(r);$("status").className=`badge ${s}`;$("status").textContent=label(s);const retired=s==="retired";$("restore").hidden=!retired;$("hard").hidden=!retired;$("retire").hidden=retired;["up","down","dup","diff","hist"].forEach(x=>$(x).disabled=!r||retired&&["up","down","dup"].includes(x));Object.values(f).forEach(x=>x.disabled=retired);document.querySelector('#form button[type="submit"]').disabled=retired}
function reset(){id=null;orig=null;$("form").reset();f.collapsed.checked=true;f.published.checked=true;options();$("editorTitle").textContent="新しいルール";preview();statusUI(null);renderRules()}
function load(r){id=+r.id;orig=structuredClone(r);f.major.value=r.major_id||"";middleOptions();f.middle.value=r.middle_id||"";f.type.value=r.display_type||"normal";f.category.value=r.category||"";f.title.value=r.title||"";f.summary.value=r.summary||"";f.content.value=r.content||"";f.details.value=r.details||"";f.collapsed.checked=!!r.details_collapsed;f.note.value="";f.published.checked=!!r.is_published;f.keywords.value=r.keywords||"";f.slug.value=r.slug||"";$("editorTitle").textContent=r.title;preview();statusUI(r);renderRules()}
function data(){return{major_id:f.major.value||null,middle_id:f.middle.value||null,display_type:f.type.value,category:f.category.value,title:f.title.value,summary:f.summary.value,content:f.content.value,details:f.details.value,details_collapsed:f.collapsed.checked,change_note:f.note.value,is_published:f.published.checked,keywords:f.keywords.value,slug:f.slug.value}}
function preview(){const ma=majors.find(x=>+x.id===+f.major.value),mi=middles.find(x=>+x.id===+f.middle.value);$("path").textContent=[ma?.title,mi?.title].filter(Boolean).join(" ＞ ")||"未分類";$("pvTitle").textContent=f.title.value||"ルール名";$("pvContent").textContent=f.content.value||"本文が表示されます。";$("pvDetails").hidden=!f.details.value.trim();$("pvDetailText").textContent=f.details.value}
async function refresh(prefer=id){const [a,b,c]=await Promise.all([api("/api/admin/rules"),api("/api/admin/majors"),api("/api/admin/middles")]),[x,y,z]=await Promise.all([a.json(),b.json(),c.json()]);rules=x.rules||[];majors=y.majors||[];middles=z.middles||[];options();renderRules();renderMaj();renderMid();if(prefer){const r=rules.find(x=>+x.id===+prefer);if(r)load(r)}}
function renderMaj(){const b=$("majorList");b.innerHTML="";majors.forEach(x=>{const d=document.createElement("div");d.className="item";d.innerHTML=`<div><b>${esc(x.title)}</b><small>大タイトル</small></div><div><button class="e">編集</button><button class="u">↑</button><button class="d">↓</button></div>`;d.querySelector(".e").onclick=async()=>{const t=prompt("大タイトル名",x.title);if(t){await api(`/api/admin/majors/${x.id}`,{method:"PUT",body:JSON.stringify({title:t})});refresh()}};d.querySelector(".u").onclick=()=>mv("majors",x.id,"up");d.querySelector(".d").onclick=()=>mv("majors",x.id,"down");b.appendChild(d)})}
function renderMid(){const b=$("middleList");b.innerHTML="";middles.forEach(x=>{const d=document.createElement("div");d.className="item";d.innerHTML=`<div><b>${esc(x.title)}</b><small>${esc(x.major_title||"未分類")}</small></div><div><button class="e">編集</button><button class="u">↑</button><button class="d">↓</button></div>`;d.querySelector(".e").onclick=async()=>{const t=prompt("中タイトル名",x.title);if(t){await api(`/api/admin/middles/${x.id}`,{method:"PUT",body:JSON.stringify({title:t,major_id:x.major_id})});refresh()}};d.querySelector(".u").onclick=()=>mv("middles",x.id,"up");d.querySelector(".d").onclick=()=>mv("middles",x.id,"down");b.appendChild(d)})}
async function mv(type,i,d){await api(`/api/admin/${type}/${i}/move`,{method:"POST",body:JSON.stringify({direction:d})});refresh(id)}
$("form").onsubmit=async e=>{e.preventDefault();const p=data();if(!p.title.trim()||!p.content.trim())return alert("ルール名と本文は必須です。");const r=await api(id?`/api/admin/rules/${id}`:"/api/admin/rules",{method:id?"PUT":"POST",body:JSON.stringify(p)}),j=await r.json();if(!r.ok)return alert("保存できませんでした。");id=j.id||id;await refresh(id);alert("保存しました。")};
Object.values(f).forEach(x=>["input","change"].forEach(ev=>x.addEventListener(ev,()=>{if(x===f.major)middleOptions();preview()})));
$("search").oninput=renderRules;$("newRule").onclick=reset;$("up").onclick=()=>mv("rules",id,"up");$("down").onclick=()=>mv("rules",id,"down");
$("dup").onclick=async()=>{const r=await api(`/api/admin/rules/${id}/duplicate`,{method:"POST"}),j=await r.json();await refresh(j.id);alert("下書きとして複製しました。")};
$("retire").onclick=async()=>{if(confirm("このルールを廃止しますか？")){await api(`/api/admin/rules/${id}/retire`,{method:"POST"});await refresh(id)}};
$("restore").onclick=async()=>{await api(`/api/admin/rules/${id}/restore`,{method:"POST"});await refresh(id);alert("下書きとして復元しました。")};
$("hard").onclick=()=>{const r=rules.find(x=>+x.id===+id),name=prompt(`完全削除は元に戻せません。\n確認のためルール名を入力してください。\n\n${r.title}`);if(name!==r.title)return; if(confirm("最終確認。本当に完全削除しますか？"))hardDelete()};
async function hardDelete(){await api(`/api/admin/rules/${id}/hard-delete`,{method:"DELETE"});await refresh();reset();alert("完全削除しました。")}
$("diff").onclick=()=>{if(!orig)return;const now=data(),pairs=[["大タイトル",orig.major_title||"未分類",majors.find(x=>+x.id===+now.major_id)?.title||"未分類"],["中タイトル",orig.middle_title||"未分類",middles.find(x=>+x.id===+now.middle_id)?.title||"未分類"],["タイトル",orig.title,now.title],["本文",orig.content,now.content],["補足",orig.details||"",now.details]].filter(x=>String(x[1])!==String(x[2]));show("変更差分",pairs.length?pairs.map(x=>`<h4>${esc(x[0])}</h4><div class="diff"><pre>${esc(x[1])}</pre><pre>${esc(x[2])}</pre></div>`).join(""):"<p>変更はありません。</p>")};
$("hist").onclick=async()=>{const r=await api(`/api/admin/history/${id}`),j=await r.json();show("変更履歴",(j.history||[]).map(x=>`<div class="item"><div><b>${esc(x.change_note||"変更前")}</b><small>${esc(x.saved_at)}</small><p>${esc(x.content)}</p></div></div>`).join("")||"<p>履歴はありません。</p>")};
function show(t,h){$("modalTitle").textContent=t;$("modalBody").innerHTML=h;$("modal").showModal()}$("close").onclick=()=>$("modal").close();
$("addMajor").onclick=async()=>{const t=prompt("新しい大タイトル名");if(t){await api("/api/admin/majors",{method:"POST",body:JSON.stringify({title:t})});refresh()}};
$("addMiddle").onclick=async()=>{if(!majors.length)return alert("先に大タイトルを作ってください。");const s=majors.map(x=>`${x.id}: ${x.title}`).join("\n"),m=+prompt(`大タイトル番号\n${s}`),t=prompt("新しい中タイトル名");if(m&&t){await api("/api/admin/middles",{method:"POST",body:JSON.stringify({major_id:m,title:t})});refresh()}};
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".pane").forEach(x=>x.hidden=x.id!==b.dataset.tab)});
document.querySelectorAll(".filters button").forEach(b=>b.onclick=()=>{filter=b.dataset.s;document.querySelectorAll(".filters button").forEach(x=>x.classList.toggle("active",x===b));renderRules()});
async function login(){token=$("token").value.trim();const r=await api("/api/admin/check");if(!r.ok)return $("msg").textContent="管理パスワードが違うか、設定が完了していません。";localStorage.setItem("northcity_admin_token",token);$("login").hidden=true;$("app").hidden=false;await refresh();reset()}
$("loginBtn").onclick=login;$("token").onkeydown=e=>{if(e.key==="Enter")login()};$("logout").onclick=()=>{localStorage.removeItem("northcity_admin_token");location.reload()};
(async()=>{if(!token)return;$("token").value=token;const r=await api("/api/admin/check");if(r.ok){$("login").hidden=true;$("app").hidden=false;await refresh();reset()}})();