const $=id=>document.getElementById(id);let token=localStorage.getItem("northcity_admin_token")||"",name=localStorage.getItem("northcity_admin_name")||"",rules=[],majors=[],middles=[],current=null,dirty=false,majorEdit=null,middleEdit=null,selectedRules=new Set;
const api=(p,o={})=>{const h=new Headers(o.headers||{});h.set("x-admin-token",token);h.set("x-admin-name",encodeURIComponent(name));if(o.body&&!(o.body instanceof FormData))h.set("content-type","application/json");return fetch(p,{...o,headers:h,cache:"no-store"})},esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
function page(p){if(dirty&&!confirm("未保存の変更があります。移動しますか？"))return;dirty=false;document.querySelectorAll(".admin-page").forEach(x=>x.hidden=x.id!==`${p}Page`);$("homeButton").hidden=p==="home";const t={home:["管理トップ","変更したいものを選んでください。"],rules:["ルール管理","ルール・カテゴリ・必読・履歴を管理します。"],images:["画像管理","サイトに表示する画像を管理します。"],news:["お知らせ管理","お知らせを追加・編集します。"],faq:["FAQ管理","よくある質問を管理します。"],settings:["サイト設定","サイトの基本情報を変更します。"]}[p];$("pageTitle").textContent=t[0];$("pageHelp").textContent=t[1];if(p==="images")loadImages();if(p==="news")loadNews();if(p==="faq")loadFaq();if(p==="settings")loadSettings()}
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>page(b.dataset.page));$("homeButton").onclick=()=>page("home");
async function refresh(){const [a,b,c]=await Promise.all([api("/api/admin/rules"),api("/api/admin/majors"),api("/api/admin/middles")]),[x,y,z]=await Promise.all([a.json(),b.json(),c.json()]);rules=x.rules||[];majors=y.majors||[];middles=z.middles||[];selectedRules=new Set([...selectedRules].filter(id=>rules.some(r=>+r.id===+id)));opts();renderRules();renderMajors();renderMiddles()}
function opts(){const mo=majors.map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join("");$("ruleMajor").innerHTML='<option value="">未分類</option>'+mo;$("middleMajor").innerHTML='<option value="">選択</option>'+mo;middleOpts()}
function middleOpts(){const v=$("ruleMiddle").value,m=+$("ruleMajor").value;$("ruleMiddle").innerHTML='<option value="">未分類</option>'+middles.filter(x=>!m||+x.major_id===m).map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join("");if([...$("ruleMiddle").options].some(o=>o.value===v))$("ruleMiddle").value=v}
function visibleRules(){const q=$("ruleSearch").value.toLowerCase();return rules.filter(r=>[r.title,r.major_title,r.middle_title].join(" ").toLowerCase().includes(q))}
function updateSelectionTools(){const visible=visibleRules(),all=visible.length>0&&visible.every(r=>selectedRules.has(+r.id));$("ruleSelectAll").checked=all;$("ruleSelectAll").indeterminate=!all&&visible.some(r=>selectedRules.has(+r.id));$("deleteSelectedRules").disabled=selectedRules.size===0;$("deleteSelectedRules").textContent=selectedRules.size?`選択したルールを削除（${selectedRules.size}件）`:"選択したルールを削除"}
function renderRules(){const list=visibleRules();$("ruleList").innerHTML=list.map(r=>`<div class="rule-row ${+r.id===+current?"active":""}" data-id="${r.id}"><label class="rule-pick" title="選択"><input type="checkbox" class="rule-select" data-id="${r.id}" ${selectedRules.has(+r.id)?"checked":""}></label><button class="rule-main"><strong>${r.is_required?"<span class='required-badge'>必読</span> ":""}${esc(r.title)}</strong><small>${esc([r.major_title,r.middle_title].filter(Boolean).join(" ＞ ")||"未分類")} ・ ${esc(r.edited_by||"")}</small></button><span class="row-status ${r.retired_at?"retired":r.is_published?"published":"draft"}">${r.retired_at?"廃止":r.is_published?"公開":"下書き"}</span></div>`).join("");document.querySelectorAll(".rule-row").forEach(x=>{x.querySelector(".rule-main").onclick=()=>loadRule(rules.find(r=>+r.id===+x.dataset.id));const cb=x.querySelector(".rule-select");cb.onchange=()=>{const id=+cb.dataset.id;cb.checked?selectedRules.add(id):selectedRules.delete(id);updateSelectionTools()}});updateSelectionTools()}
function mark(){dirty=true;$("unsaved").hidden=false}
function resetRule(){current=null;$("ruleForm").reset();$("ruleCollapsed").checked=true;$("unsaved").hidden=true;dirty=false;opts();$("ruleEditorTitle").textContent="新しいルール";renderRules();state()}
function loadRule(r){if(dirty&&!confirm("未保存の変更があります。破棄しますか？"))return;current=+r.id;dirty=false;$("unsaved").hidden=true;$("ruleMajor").value=r.major_id||"";middleOpts();$("ruleMiddle").value=r.middle_id||"";$("ruleRequired").checked=!!r.is_required;$("ruleTitle").value=r.title||"";$("ruleSummary").value=r.summary||"";$("ruleContent").value=r.content||"";$("ruleDetails").value=r.details||"";$("ruleCollapsed").checked=!!r.details_collapsed;$("ruleType").value=r.display_type||"normal";$("ruleLayout").value=r.layout_type||"text";$("ruleTags").value=r.tags||"";$("ruleNote").value="";$("rulePublished").checked=!!r.is_published;$("ruleKeywords").value=r.keywords||"";$("ruleSlug").value=r.slug||"";$("ruleEditorTitle").textContent=r.title;state(r);renderRules()}
function state(r=rules.find(x=>+x.id===+current)){const retired=!!r?.retired_at;$("ruleStatus").textContent=retired?"廃止済み":$("rulePublished").checked?"公開中":"下書き";document.querySelector('#ruleForm button[type="submit"]').disabled=retired}
$("ruleForm").oninput=mark;$("ruleMajor").onchange=()=>{middleOpts();mark()};$("ruleForm").onsubmit=async e=>{e.preventDefault();const b={major_id:$("ruleMajor").value||null,middle_id:$("ruleMiddle").value||null,is_required:$("ruleRequired").checked,title:$("ruleTitle").value,summary:$("ruleSummary").value,content:$("ruleContent").value,details:$("ruleDetails").value,details_collapsed:$("ruleCollapsed").checked,display_type:$("ruleType").value,layout_type:$("ruleLayout").value,tags:$("ruleTags").value,change_note:$("ruleNote").value,is_published:$("rulePublished").checked,keywords:$("ruleKeywords").value,slug:$("ruleSlug").value};if(!b.title.trim()||!b.content.trim())return alert("ルール名と本文は必須です。");const r=await api(current?`/api/admin/rules/${current}`:"/api/admin/rules",{method:current?"PUT":"POST",body:JSON.stringify(b)}),j=await r.json();current=j.id||current;dirty=false;$("unsaved").hidden=true;await refresh();if(current)loadRule(rules.find(x=>+x.id===+current));alert("保存しました。")};
$("newRule").onclick=resetRule;$("ruleSearch").oninput=renderRules;async function mv(t,id,d){await api(`/api/admin/${t}/${id}/move`,{method:"POST",body:JSON.stringify({direction:d})});await refresh()}$("ruleUp").onclick=()=>current&&mv("rules",current,"up");$("ruleDown").onclick=()=>current&&mv("rules",current,"down");
$("ruleSelectAll").onchange=()=>{const ids=visibleRules().map(r=>+r.id);if($("ruleSelectAll").checked)ids.forEach(id=>selectedRules.add(id));else ids.forEach(id=>selectedRules.delete(id));renderRules()};
$("deleteSelectedRules").onclick=async()=>{if(!selectedRules.size)return;const chosen=rules.filter(r=>selectedRules.has(+r.id));const names=chosen.slice(0,8).map(r=>`・${r.title}`).join("\n")+(chosen.length>8?`\nほか ${chosen.length-8}件`:"");if(!confirm(`選択した ${chosen.length}件のルールを削除します。\n\n${names}\n\n削除すると元に戻せません。よろしいですか？`))return;const r=await api("/api/admin/rules/delete-selected",{method:"DELETE",body:JSON.stringify({ids:[...selectedRules]})}),j=await r.json();if(!r.ok)return alert(j.message||"削除できませんでした。");if(current&&selectedRules.has(+current))current=null;selectedRules.clear();dirty=false;await refresh();if(!current)resetRule();alert(`${j.deleted||chosen.length}件のルールを削除しました。`)};

function richText(v){const e=esc(v||"");const lines=e.split("\n");let out="",inList=false;for(const line of lines){if(line.startsWith("## ")){if(inList){out+="</ul>";inList=false}out+=`<h2>${line.slice(3)}</h2>`;continue}if(line.startsWith("- ")){if(!inList){out+="<ul>";inList=true}out+=`<li>${line.slice(2).replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>")}</li>`;continue}if(inList){out+="</ul>";inList=false}let x=line.replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/`(.+?)`/g,"<code>$1</code>");out+=x?`<p>${x}</p>`:""}if(inList)out+="</ul>";return out}
document.querySelectorAll(".rich-toolbar button").forEach(b=>b.onclick=()=>{const ta=$(b.closest(".rich-toolbar").dataset.target),a=ta.selectionStart,z=ta.selectionEnd,sel=ta.value.slice(a,z);if(b.dataset.wrap){const w=b.dataset.wrap;ta.setRangeText(w+sel+w,a,z,"end")}else{const pre=b.dataset.prefix||"";ta.setRangeText(pre+sel,a,z,"end")}ta.focus();mark()});
$("rulePreview").onclick=()=>{const tags=$("ruleTags").value.split(",").map(x=>x.trim()).filter(Boolean);show("プレビュー",`<article class="rule-preview"><small>${esc($("ruleLayout").selectedOptions[0]?.textContent||"")} / ${esc($("ruleType").selectedOptions[0]?.textContent||"")}</small><h1>${esc($("ruleTitle").value||"無題")}</h1>${$("ruleSummary").value?`<p><strong>${esc($("ruleSummary").value)}</strong></p>`:""}${tags.length?`<div class="preview-tags">${tags.map(x=>`<span>${esc(x)}</span>`).join("")}</div>`:""}${richText($("ruleContent").value)}${$("ruleDetails").value?`<details><summary>詳しく見る</summary>${richText($("ruleDetails").value)}</details>`:""}</article>`)};
$("ruleDuplicate").onclick=()=>{if(!current)return alert("複製するルールを選んでください。");const r=rules.find(x=>+x.id===+current);current=null;$("ruleTitle").value=(r.title||"")+"（コピー）";$("ruleSlug").value="";$("rulePublished").checked=false;$("ruleNote").value="複製して作成";$("ruleEditorTitle").textContent="複製したルール";mark();state()};
$("ruleHistory").onclick=async()=>{if(!current)return;const j=await (await api(`/api/admin/history/${current}`)).json();show("変更履歴",(j.history||[]).map(x=>`<div class="history-item"><strong>${esc(x.change_note||"変更")}</strong><small>${esc(x.saved_at)} / ${esc(x.edited_by||"運営")}</small><p>${esc(x.content)}</p></div>`).join("")||"<p>履歴なし</p>")};
function renderMajors(){$("majorList").innerHTML=majors.map(x=>`<div class="title-item"><div><strong>${x.is_required?"<span class='required-badge'>必読</span> ":""}${esc(x.title)}</strong><small>${esc(x.description||"説明なし")} / 更新: ${esc(x.edited_by||"")}</small></div><div class="title-actions"><button class="tiny edit" data-id="${x.id}">編集</button><button class="tiny up" data-id="${x.id}">↑</button><button class="tiny down" data-id="${x.id}">↓</button></div></div>`).join("");$("majorList").querySelectorAll(".edit").forEach(b=>b.onclick=()=>{const x=majors.find(v=>+v.id===+b.dataset.id);majorEdit=x.id;$("majorTitle").value=x.title;$("majorDescription").value=x.description||"";$("majorRequired").checked=!!x.is_required;$("majorSave").textContent="変更を保存";$("majorCancel").hidden=false});$("majorList").querySelectorAll(".up").forEach(b=>b.onclick=()=>mv("majors",b.dataset.id,"up"));$("majorList").querySelectorAll(".down").forEach(b=>b.onclick=()=>mv("majors",b.dataset.id,"down"))}
$("majorSave").onclick=async()=>{const b={title:$("majorTitle").value,description:$("majorDescription").value,is_required:$("majorRequired").checked};if(!b.title.trim())return;await api(majorEdit?`/api/admin/majors/${majorEdit}`:"/api/admin/majors",{method:majorEdit?"PUT":"POST",body:JSON.stringify(b)});majorEdit=null;$("majorTitle").value=$("majorDescription").value="";$("majorRequired").checked=false;$("majorSave").textContent="追加";$("majorCancel").hidden=true;await refresh()};$("majorCancel").onclick=()=>{majorEdit=null;$("majorTitle").value=$("majorDescription").value="";$("majorRequired").checked=false;$("majorSave").textContent="追加";$("majorCancel").hidden=true};
function renderMiddles(){const m=+$("middleMajor").value;$("middleList").innerHTML=!m?"<p class='help'>大タイトルを選んでください。</p>":middles.filter(x=>+x.major_id===m).map(x=>`<div class="title-item"><div><strong>${x.is_required?"<span class='required-badge'>必読</span> ":""}${esc(x.title)}</strong><small>${esc(x.description||"説明なし")}</small></div><div class="title-actions"><button class="tiny edit" data-id="${x.id}">編集</button><button class="tiny up" data-id="${x.id}">↑</button><button class="tiny down" data-id="${x.id}">↓</button></div></div>`).join("");$("middleList").querySelectorAll(".edit").forEach(b=>b.onclick=()=>{const x=middles.find(v=>+v.id===+b.dataset.id);middleEdit=x.id;$("middleTitle").value=x.title;$("middleDescription").value=x.description||"";$("middleRequired").checked=!!x.is_required;$("middleSave").textContent="変更を保存";$("middleCancel").hidden=false});$("middleList").querySelectorAll(".up").forEach(b=>b.onclick=()=>mv("middles",b.dataset.id,"up"));$("middleList").querySelectorAll(".down").forEach(b=>b.onclick=()=>mv("middles",b.dataset.id,"down"))}
$("middleMajor").onchange=renderMiddles;$("middleSave").onclick=async()=>{const b={major_id:$("middleMajor").value,title:$("middleTitle").value,description:$("middleDescription").value,is_required:$("middleRequired").checked};if(!b.major_id||!b.title.trim())return alert("大タイトルと中タイトル名が必要です。");await api(middleEdit?`/api/admin/middles/${middleEdit}`:"/api/admin/middles",{method:middleEdit?"PUT":"POST",body:JSON.stringify(b)});middleEdit=null;$("middleTitle").value=$("middleDescription").value="";$("middleRequired").checked=false;$("middleSave").textContent="追加";$("middleCancel").hidden=true;await refresh();renderMiddles()};$("middleCancel").onclick=()=>{middleEdit=null;$("middleTitle").value=$("middleDescription").value="";$("middleRequired").checked=false;$("middleSave").textContent="追加";$("middleCancel").hidden=true};
document.querySelectorAll("[data-rule-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-rule-tab]").forEach(x=>x.classList.toggle("active",x===b));["small","middle","major"].forEach(x=>$(`${x}Tab`).hidden=x!==b.dataset.ruleTab)});
async function loadImages(){const j=await (await api("/api/admin/images")).json();$("r2Warning").hidden=!!j.r2;$("imageList").innerHTML=(j.items||[]).map(x=>`<div class="media-item"><img src="/media/${encodeURIComponent(x.object_key)}" onerror="this.closest('.media-item').style.display='none'"><div><strong>${esc(x.title||x.slot)}</strong><small>${esc(x.slot)}</small><button class="tiny image-del" data-id="${x.id}">削除</button></div></div>`).join("")||"<p class='help'>画像はまだありません。</p>";document.querySelectorAll(".image-del").forEach(b=>b.onclick=async()=>{if(confirm("画像を削除しますか？")){await api(`/api/admin/images/${b.dataset.id}`,{method:"DELETE"});loadImages()}})}
$("imageForm").onsubmit=async e=>{e.preventDefault();const file=$("imageFile").files[0];if(!file)return alert("画像を選んでください。");const f=new FormData();f.append("file",file);f.append("slot",$("imageSlot").value);f.append("title",$("imageTitle").value);f.append("alt_text",$("imageAlt").value);const r=await api("/api/admin/images/upload",{method:"POST",body:f}),j=await r.json();if(!r.ok)return alert(j.message||"アップロードできませんでした。");e.target.reset();loadImages()};
async function loadNews(){const j=await (await api("/api/admin/announcements")).json();$("newsList").innerHTML=(j.items||[]).map(x=>`<div class="title-item"><div><strong>${x.is_important?"<span class='required-badge'>重要</span> ":""}${esc(x.title)}</strong><small>${x.is_published?"公開":"下書き"} / ${esc(x.edited_by||"")}</small></div><button class="tiny news-edit" data-id="${x.id}">編集</button></div>`).join("");document.querySelectorAll(".news-edit").forEach(b=>b.onclick=()=>{const x=j.items.find(v=>+v.id===+b.dataset.id);$("newsId").value=x.id;$("newsTitle").value=x.title;$("newsBody").value=x.body;$("newsTag").value=x.tag;$("newsImportant").checked=!!x.is_important;$("newsPublished").checked=!!x.is_published})}
$("newsSave").onclick=async()=>{const id=$("newsId").value,b={title:$("newsTitle").value,body:$("newsBody").value,tag:$("newsTag").value,is_important:$("newsImportant").checked,is_published:$("newsPublished").checked};await api(id?`/api/admin/announcements/${id}`:"/api/admin/announcements",{method:id?"PUT":"POST",body:JSON.stringify(b)});newsReset();loadNews()};function newsReset(){$("newsId").value=$("newsTitle").value=$("newsBody").value="";$("newsImportant").checked=$("newsPublished").checked=false}$("newsReset").onclick=newsReset;
async function loadFaq(){const j=await (await api("/api/admin/faqs")).json();$("faqList").innerHTML=(j.items||[]).map(x=>`<div class="title-item"><div><strong>${esc(x.question)}</strong><small>${esc(x.category)} / ${x.is_published?"公開":"下書き"}</small></div><button class="tiny faq-edit" data-id="${x.id}">編集</button></div>`).join("");document.querySelectorAll(".faq-edit").forEach(b=>b.onclick=()=>{const x=j.items.find(v=>+v.id===+b.dataset.id);$("faqId").value=x.id;$("faqCategory").value=x.category;$("faqQuestion").value=x.question;$("faqAnswer").value=x.answer;$("faqPublished").checked=!!x.is_published})}
$("faqSave").onclick=async()=>{const id=$("faqId").value,b={category:$("faqCategory").value,question:$("faqQuestion").value,answer:$("faqAnswer").value,is_published:$("faqPublished").checked};await api(id?`/api/admin/faqs/${id}`:"/api/admin/faqs",{method:id?"PUT":"POST",body:JSON.stringify(b)});faqReset();loadFaq()};function faqReset(){$("faqId").value=$("faqCategory").value=$("faqQuestion").value=$("faqAnswer").value="";$("faqPublished").checked=false}$("faqReset").onclick=faqReset;
async function loadSettings(){const j=await (await api("/api/admin/settings")).json(),s=j.settings||{};$("setSeason").value=s.season||"";$("setSeasonNote").value=s.season_note||"";$("setOpen").value=s.open_time||"";$("setRestart").value=s.restart_time||"";$("setCrime").value=s.crime_time||"";$("setCrimeNote").value=s.crime_note||"";$("setDiscord").value=s.discord_url||"";$("setX").value=s.x_url||"";$("setHeroTitle").value=s.hero_title||"";$("setHeroCopy").value=s.hero_copy||"";$("setNoticeEnabled").checked=s.important_notice_enabled==="1";$("setNoticeText").value=s.important_notice_text||""}
$("settingsSave").onclick=async()=>{const b={season:$("setSeason").value,season_note:$("setSeasonNote").value,open_time:$("setOpen").value,restart_time:$("setRestart").value,crime_time:$("setCrime").value,crime_note:$("setCrimeNote").value,discord_url:$("setDiscord").value,x_url:$("setX").value,hero_title:$("setHeroTitle").value,hero_copy:$("setHeroCopy").value,important_notice_enabled:$("setNoticeEnabled").checked?"1":"0",important_notice_text:$("setNoticeText").value};await api("/api/admin/settings",{method:"PUT",body:JSON.stringify(b)});alert("保存しました。")};
function show(t,h){$("dialogTitle").textContent=t;$("dialogBody").innerHTML=h;$("dialog").showModal()}$("dialogClose").onclick=()=>$("dialog").close();window.addEventListener("beforeunload",e=>{if(dirty){e.preventDefault();e.returnValue=""}});
async function login(){token=$("adminToken").value.trim();name=$("adminName").value.trim();if(!name)return $("loginMessage").textContent="運営名を入力してください。";const r=await api("/api/admin/check");if(!r.ok)return $("loginMessage").textContent="管理パスワードが違うか設定が完了していません。";localStorage.setItem("northcity_admin_token",token);localStorage.setItem("northcity_admin_name",name);$("loginView").hidden=true;$("adminView").hidden=false;await refresh();resetRule();const d=await (await api("/api/admin/dashboard")).json();$("dashboardNote").innerHTML=`<strong>現在の登録状況</strong><p>ルール ${d.counts.rules}件 / お知らせ ${d.counts.announcements}件 / FAQ ${d.counts.faqs}件 / 画像 ${d.counts.images}件</p>${d.r2?"":"<p class='warning'>画像管理のR2はまだ未接続です。</p>"}`}
$("loginButton").onclick=login;$("adminToken").onkeydown=e=>{if(e.key==="Enter")login()};$("logoutButton").onclick=()=>{localStorage.removeItem("northcity_admin_token");location.reload()};
(async()=>{if(!token||!name)return;$("adminToken").value=token;$("adminName").value=name;const r=await api("/api/admin/check");if(r.ok){$("loginView").hidden=true;$("adminView").hidden=false;await refresh();resetRule();const d=await (await api("/api/admin/dashboard")).json();$("dashboardNote").innerHTML=`<strong>現在の登録状況</strong><p>ルール ${d.counts.rules}件 / お知らせ ${d.counts.announcements}件 / FAQ ${d.counts.faqs}件 / 画像 ${d.counts.images}件</p>${d.r2?"":"<p class='warning'>画像管理のR2はまだ未接続です。</p>"}`}})();