const menuToggle=document.getElementById("menuToggle"),mainNav=document.getElementById("mainNav");menuToggle?.addEventListener("click",()=>{const o=mainNav.classList.toggle("open");menuToggle.setAttribute("aria-expanded",String(o))});mainNav?.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{mainNav.classList.remove("open");menuToggle?.setAttribute("aria-expanded","false")}));
const $=id=>document.getElementById(id),esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");let rules=[];
function uniq(a,k){const s=new Set;return a.filter(x=>{const v=k(x);if(s.has(v))return false;s.add(v);return true})}const major=id=>rules.find(r=>+r.major_id===+id)?.major_title||"未分類",middle=id=>rules.find(r=>+r.middle_id===+id)?.middle_title||"未分類";
function badge(v){return v?'<span class="required-public">必読</span>':""}function tools(label,fn,parts){const d=document.createElement("div");d.className="rule-nav-tools";if(label){const b=document.createElement("button");b.className="rule-nav-back";b.textContent=`← ${label}`;b.onclick=fn;d.appendChild(b)}const p=document.createElement("div");p.className="rule-breadcrumb";p.textContent=parts.filter(Boolean).join(" ＞ ");d.appendChild(p);return d}
function card(t,sub,req,icon,fn){const b=document.createElement("button");b.className="rule-card rule-nav-card";b.innerHTML=`<span class="rule-icon">${icon}</span><strong>${badge(req)}${esc(t)}</strong><span>${esc(sub||"")}</span>`;b.onclick=fn;return b}
function majors(){const g=$("ruleGrid");g.innerHTML="";uniq(rules.filter(r=>r.major_id&&r.major_title),r=>+r.major_id).forEach(x=>{const n=rules.filter(r=>+r.major_id===+x.major_id).length;g.appendChild(card(x.major_title,x.major_description||`${n}件のルール`,x.major_required,"📁",()=>middles(x.major_id)))})}
function middles(mid){const g=$("ruleGrid");g.innerHTML="";g.appendChild(tools("大タイトル一覧",majors,["ルール一覧",major(mid)]));const a=rules.filter(r=>+r.major_id===+mid),ms=uniq(a.filter(r=>r.middle_id&&r.middle_title),r=>+r.middle_id);if(!ms.length)return a.forEach(r=>g.appendChild(rcard(r)));ms.forEach(x=>{const n=a.filter(r=>+r.middle_id===+x.middle_id).length;g.appendChild(card(x.middle_title,x.middle_description||`${n}件のルール`,x.middle_required,"📂",()=>list(mid,x.middle_id)))})}
function rcard(r){return card(r.title,r.summary||"ルールを確認",r.is_required,"📄",()=>detail(r.id))}
function list(ma,mi){const g=$("ruleGrid");g.innerHTML="";g.appendChild(tools(major(ma),()=>middles(ma),["ルール一覧",major(ma),middle(mi)]));rules.filter(r=>+r.middle_id===+mi).forEach(r=>g.appendChild(rcard(r)))}
function rich(v){const e=esc(v||""),ls=e.split("\n");let o="",ul=false;for(const l of ls){if(l.startsWith("## ")){if(ul){o+="</ul>";ul=false}o+=`<h4>${l.slice(3)}</h4>`;continue}if(l.startsWith("- ")){if(!ul){o+="<ul>";ul=true}o+=`<li>${l.slice(2).replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>")}</li>`;continue}if(ul){o+="</ul>";ul=false}const x=l.replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/`(.+?)`/g,"<mark>$1</mark>");if(x)o+=`<p>${x}</p>`}if(ul)o+="</ul>";return o}
function detail(id){const r=rules.find(x=>+x.id===+id),g=$("ruleGrid");if(!r)return;g.innerHTML="";g.appendChild(tools(r.middle_id?middle(r.middle_id):major(r.major_id),r.middle_id?()=>list(r.major_id,r.middle_id):()=>middles(r.major_id),["ルール一覧",r.major_title,r.middle_title,r.title]));const a=document.createElement("article");a.className="rule-detail-card";a.innerHTML=`<div class="rule-detail-meta">${badge(r.is_required)}${esc([r.major_title,r.middle_title].filter(Boolean).join(" ＞ "))}</div><h3>${esc(r.title)}</h3>${r.summary?`<p class="rule-detail-summary">${esc(r.summary)}</p>`:""}${r.tags?`<div class="rule-public-tags">${r.tags.split(",").map(x=>x.trim()).filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join("")}</div>`:""}<div class="rule-detail-content layout-${esc(r.layout_type||"text")}">${rich(r.content)}</div>${r.details?`<details class="rule-detail-extra" ${r.details_collapsed?"":"open"}><summary>詳しく見る</summary><div>${rich(r.details)}</div></details>`:""}`;g.appendChild(a)}
$("ruleSearch")?.addEventListener("input",e=>{const q=e.target.value.trim().toLowerCase();if(!q)return majors();const g=$("ruleGrid");g.innerHTML="";g.appendChild(tools("大タイトル一覧",majors,[`検索結果：「${q}」`]));const m=rules.filter(r=>[r.major_title,r.middle_title,r.title,r.summary,r.content,r.details,r.keywords].join(" ").toLowerCase().includes(q));if(!m.length)g.innerHTML+='<p class="no-results" style="display:block">該当するルールがありません。</p>';else m.forEach(r=>g.appendChild(rcard(r)))});
function applySettings(s){document.querySelector(".hero h1").textContent=s.hero_title||"ないなら作ればいい";document.querySelector(".hero-copy").textContent=s.hero_copy||"";const infos=document.querySelectorAll(".info-card");if(infos[0]){infos[0].querySelector("strong").textContent=s.season||"";infos[0].querySelector("small").textContent=s.season_note||""}if(infos[1]){infos[1].querySelector("strong").textContent=s.open_time||"";infos[1].querySelector("small").textContent=s.restart_time||""}if(infos[2]){infos[2].querySelector("strong").textContent=s.crime_time||"";infos[2].querySelector("small").textContent=s.crime_note||""}document.querySelectorAll('a[href*="discord.gg"]').forEach(a=>{if(s.discord_url)a.href=s.discord_url});document.querySelectorAll('a[href*="x.com"]').forEach(a=>{if(s.x_url)a.href=s.x_url});const strip=document.querySelector(".notice-strip");if(strip){strip.style.display=s.important_notice_enabled==="1"?"":"none";const a=strip.querySelector("a");if(a)a.firstChild.textContent=(s.important_notice_text||"最新のお知らせを確認する")+" "}}
function renderNews(a){const g=document.querySelector(".news-grid");if(!g)return;if(!a.length){document.getElementById("news").style.display="none";return}g.innerHTML=a.slice(0,6).map((x,i)=>`<article class="news-card ${x.is_important?"news-featured":""}"><div class="news-card-body"><div class="meta">${x.is_important?'<span class="tag tag-important">重要</span>':`<span class="tag tag-update">${esc(x.tag)}</span>`}</div><h3>${esc(x.title)}</h3><p>${esc(x.body).replaceAll("\n","<br>")}</p></div></article>`).join("")}
function renderFaq(a){const g=document.querySelector(".faq-list");if(!g)return;if(!a.length){document.getElementById("faq").style.display="none";return}g.innerHTML=a.map(x=>`<details><summary>${esc(x.question)}</summary><p>${esc(x.answer).replaceAll("\n","<br>")}</p></details>`).join("")}
function openGalleryImage(src,alt=""){let o=$("galleryLightbox");if(!o){o=document.createElement("div");o.id="galleryLightbox";o.className="gallery-lightbox";o.innerHTML='<button class="gallery-lightbox-close" type="button" aria-label="閉じる">×</button><img alt="">';document.body.appendChild(o);o.querySelector("button").onclick=()=>o.classList.remove("open");o.onclick=e=>{if(e.target===o)o.classList.remove("open")};document.addEventListener("keydown",e=>{if(e.key==="Escape")o.classList.remove("open")})}const im=o.querySelector("img");im.src=src;im.alt=alt;o.classList.add("open")}
function setupGalleryCarousel(){const track=document.querySelector(".gallery-grid"),vp=document.querySelector(".gallery-viewport"),prev=document.querySelector(".gallery-prev"),next=document.querySelector(".gallery-next");if(!track||!vp||!prev||!next)return;const update=()=>{const max=vp.scrollWidth-vp.clientWidth;prev.disabled=vp.scrollLeft<8;next.disabled=vp.scrollLeft>max-8;const one=track.children.length<=1;prev.style.display=one?"none":"";next.style.display=one?"none":""};const step=()=>Math.max(vp.clientWidth*.82,260);prev.onclick=()=>vp.scrollBy({left:-step(),behavior:"smooth"});next.onclick=()=>vp.scrollBy({left:step(),behavior:"smooth"});vp.addEventListener("scroll",update,{passive:true});window.addEventListener("resize",update);setTimeout(update,80)}
function renderImages(a){const gallery=a.filter(x=>x.slot==="gallery"),gg=document.querySelector(".gallery-grid");if(gg){if(!gallery.length)document.getElementById("gallery").style.display="none";else{gg.innerHTML="";gallery.forEach(x=>{const b=document.createElement("button");b.type="button";b.className="gallery-item dynamic-image gallery-open";const im=document.createElement("img");im.src="/media/"+encodeURIComponent(x.object_key);im.alt=x.alt_text||x.title||"";im.onerror=()=>b.remove();b.appendChild(im);b.onclick=()=>openGalleryImage(im.src,im.alt);gg.appendChild(b)});setupGalleryCarousel()}}const hero=a.find(x=>x.slot==="hero");if(hero){const h=document.querySelector(".hero-content");const im=document.createElement("img");im.className="managed-hero-image";im.src="/media/"+encodeURIComponent(hero.object_key);im.alt=hero.alt_text||hero.title||"";im.onerror=()=>im.remove();h.prepend(im)}}
(async()=>{try{const j=await (await fetch("/api/public",{cache:"no-store"})).json();if(!j.ok)throw 0;rules=j.rules||[];applySettings(j.settings||{});renderNews(j.announcements||[]);renderFaq(j.faqs||[]);renderImages(j.images||[]);majors()}catch(e){$("ruleGrid").innerHTML='<p class="no-results" style="display:block">ルールを読み込めませんでした。</p>'}})();