function J(d,s=200){return new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json;charset=UTF-8","cache-control":"no-store"}})}
const U=()=>J({ok:false,message:"Unauthorized"},401);
const admin=(r,e)=>!!(e.ADMIN_TOKEN&&r.headers.get("x-admin-token")===e.ADMIN_TOKEN);
const S=v=>String(v??"");
async function cols(db,t){const r=await db.prepare(`PRAGMA table_info(${t})`).all();return new Set((r.results||[]).map(x=>x.name))}
async function schema(db){
  const c=await cols(db,"rules");
  for(const [n,d] of [["keywords","TEXT DEFAULT ''"],["details","TEXT DEFAULT ''"],["details_collapsed","INTEGER DEFAULT 1"],["change_note","TEXT DEFAULT ''"],["new_until","TEXT"],["retired_at","TEXT"],["major_id","INTEGER"],["middle_id","INTEGER"]]) if(!c.has(n)) await db.prepare(`ALTER TABLE rules ADD COLUMN ${n} ${d}`).run();
  await db.prepare(`CREATE TABLE IF NOT EXISTS rule_major_titles(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,sort_order INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`).run();
  await db.prepare(`CREATE TABLE IF NOT EXISTS rule_middle_titles(id INTEGER PRIMARY KEY AUTOINCREMENT,major_id INTEGER NOT NULL,title TEXT NOT NULL,sort_order INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`).run();
  await db.prepare(`CREATE TABLE IF NOT EXISTS rule_history(id INTEGER PRIMARY KEY AUTOINCREMENT,rule_id INTEGER NOT NULL,title TEXT,category TEXT,summary TEXT,content TEXT,details TEXT,display_type TEXT,is_published INTEGER,change_note TEXT,saved_at TEXT DEFAULT CURRENT_TIMESTAMP)`).run();
}
function plus5(){const d=new Date();d.setUTCDate(d.getUTCDate()+5);return d.toISOString()}
async function maxSort(db,t,w="",b=[]){const r=await db.prepare(`SELECT COALESCE(MAX(sort_order),-1)+1 n FROM ${t} ${w}`).bind(...b).first();return Number(r?.n||0)}
async function move(db,t,id,dir,scope=null){
  const r=await db.prepare(`SELECT * FROM ${t} WHERE id=?`).bind(id).first(); if(!r)return;
  const op=dir==="up"?"<":">", ord=dir==="up"?"DESC":"ASC"; let q=`SELECT * FROM ${t} WHERE sort_order ${op} ?`, b=[r.sort_order];
  if(scope){q+=` AND ${scope}=?`;b.push(r[scope])} q+=` ORDER BY sort_order ${ord},id ${ord} LIMIT 1`;
  const o=await db.prepare(q).bind(...b).first();if(!o)return;
  await db.batch([db.prepare(`UPDATE ${t} SET sort_order=? WHERE id=?`).bind(o.sort_order,r.id),db.prepare(`UPDATE ${t} SET sort_order=? WHERE id=?`).bind(r.sort_order,o.id)]);
}
async function hist(db,r,n=""){if(!r)return;await db.prepare(`INSERT INTO rule_history(rule_id,title,category,summary,content,details,display_type,is_published,change_note) VALUES(?,?,?,?,?,?,?,?,?)`).bind(r.id,r.title,r.category||"",r.summary||"",r.content||"",r.details||"",r.display_type||"normal",r.is_published??1,n).run()}
function slugify(t){return S(t).normalize("NFKC").toLowerCase().replace(/[^\p{Letter}\p{Number}]+/gu,"-").replace(/^-+|-+$/g,"").slice(0,80)||`rule-${Date.now()}`}
async function unique(db,s,t,except=null){let b=S(s).trim()||slugify(t),c=b,n=2;while(true){const f=except?await db.prepare("SELECT id FROM rules WHERE slug=? AND id!=?").bind(c,except).first():await db.prepare("SELECT id FROM rules WHERE slug=?").bind(c).first();if(!f)return c;c=`${b}-${n++}`}}
function norm(b){const title=S(b.title).trim(),content=S(b.content).trim();if(!title||!content)return null;return{title,content,category:S(b.category).trim(),summary:S(b.summary).trim(),details:S(b.details).trim(),details_collapsed:b.details_collapsed?1:0,keywords:S(b.keywords).trim(),display_type:["normal","note","caution","important","prohibited"].includes(b.display_type)?b.display_type:"normal",is_published:b.is_published?1:0,change_note:S(b.change_note).trim(),major_id:b.major_id?Number(b.major_id):null,middle_id:b.middle_id?Number(b.middle_id):null}}
export default{async fetch(req,env){const u=new URL(req.url);
  if(u.pathname==="/api/rules"){
    try{await schema(env.DB);const r=await env.DB.prepare(`SELECT r.*,ma.title major_title,mi.title middle_title FROM rules r LEFT JOIN rule_major_titles ma ON ma.id=r.major_id LEFT JOIN rule_middle_titles mi ON mi.id=r.middle_id WHERE r.is_published=1 AND r.retired_at IS NULL ORDER BY COALESCE(ma.sort_order,99999),COALESCE(mi.sort_order,99999),r.sort_order,r.id`).all();return J({ok:true,rules:r.results||[]})}catch(e){return J({ok:false,rules:[],error:S(e.message)},500)}
  }
  if(u.pathname==="/api/admin/check"){if(!admin(req,env))return U();await schema(env.DB);return J({ok:true})}
  if(u.pathname.startsWith("/api/admin/")){
    if(!admin(req,env))return U();await schema(env.DB);
    if(u.pathname==="/api/admin/majors"&&req.method==="GET"){const r=await env.DB.prepare("SELECT * FROM rule_major_titles ORDER BY sort_order,id").all();return J({ok:true,majors:r.results||[]})}
    if(u.pathname==="/api/admin/majors"&&req.method==="POST"){const b=await req.json(),t=S(b.title).trim();if(!t)return J({ok:false},400);const n=await maxSort(env.DB,"rule_major_titles"),r=await env.DB.prepare("INSERT INTO rule_major_titles(title,sort_order) VALUES(?,?)").bind(t,n).run();return J({ok:true,id:r.meta.last_row_id})}
    let m=u.pathname.match(/^\/api\/admin\/majors\/(\d+)\/move$/);if(m){const b=await req.json();await move(env.DB,"rule_major_titles",+m[1],b.direction);return J({ok:true})}
    m=u.pathname.match(/^\/api\/admin\/majors\/(\d+)$/);if(m&&req.method==="PUT"){const b=await req.json();await env.DB.prepare("UPDATE rule_major_titles SET title=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(S(b.title).trim(),+m[1]).run();return J({ok:true})}
    if(u.pathname==="/api/admin/middles"&&req.method==="GET"){const r=await env.DB.prepare("SELECT mi.*,ma.title major_title FROM rule_middle_titles mi LEFT JOIN rule_major_titles ma ON ma.id=mi.major_id ORDER BY COALESCE(ma.sort_order,99999),mi.sort_order,mi.id").all();return J({ok:true,middles:r.results||[]})}
    if(u.pathname==="/api/admin/middles"&&req.method==="POST"){const b=await req.json(),t=S(b.title).trim(),mid=+b.major_id;if(!t||!mid)return J({ok:false},400);const n=await maxSort(env.DB,"rule_middle_titles","WHERE major_id=?",[mid]),r=await env.DB.prepare("INSERT INTO rule_middle_titles(major_id,title,sort_order) VALUES(?,?,?)").bind(mid,t,n).run();return J({ok:true,id:r.meta.last_row_id})}
    m=u.pathname.match(/^\/api\/admin\/middles\/(\d+)\/move$/);if(m){const b=await req.json();await move(env.DB,"rule_middle_titles",+m[1],b.direction,"major_id");return J({ok:true})}
    m=u.pathname.match(/^\/api\/admin\/middles\/(\d+)$/);if(m&&req.method==="PUT"){const b=await req.json();await env.DB.prepare("UPDATE rule_middle_titles SET title=?,major_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(S(b.title).trim(),+b.major_id,+m[1]).run();return J({ok:true})}
    if(u.pathname==="/api/admin/rules"&&req.method==="GET"){const r=await env.DB.prepare(`SELECT r.*,ma.title major_title,mi.title middle_title FROM rules r LEFT JOIN rule_major_titles ma ON ma.id=r.major_id LEFT JOIN rule_middle_titles mi ON mi.id=r.middle_id ORDER BY CASE WHEN r.retired_at IS NULL THEN 0 ELSE 1 END,COALESCE(ma.sort_order,99999),COALESCE(mi.sort_order,99999),r.sort_order,r.id`).all();return J({ok:true,rules:r.results||[]})}
    if(u.pathname==="/api/admin/rules"&&req.method==="POST"){const b=await req.json(),x=norm(b);if(!x)return J({ok:false},400);const sl=await unique(env.DB,b.slug,x.title),n=await maxSort(env.DB,"rules",x.middle_id?"WHERE middle_id=?":"WHERE middle_id IS NULL",x.middle_id?[x.middle_id]:[]);const r=await env.DB.prepare(`INSERT INTO rules(slug,category,title,summary,content,display_type,is_published,sort_order,keywords,details,details_collapsed,change_note,new_until,major_id,middle_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(sl,x.category,x.title,x.summary,x.content,x.display_type,x.is_published,n,x.keywords,x.details,x.details_collapsed,x.change_note,plus5(),x.major_id,x.middle_id).run();return J({ok:true,id:r.meta.last_row_id,slug:sl})}
    m=u.pathname.match(/^\/api\/admin\/rules\/(\d+)$/);if(m&&req.method==="PUT"){const id=+m[1],old=await env.DB.prepare("SELECT * FROM rules WHERE id=?").bind(id).first(),b=await req.json(),x=norm(b);if(!old||!x)return J({ok:false},400);await hist(env.DB,old,x.change_note);const sl=await unique(env.DB,b.slug||old.slug,x.title,id);await env.DB.prepare(`UPDATE rules SET slug=?,category=?,title=?,summary=?,content=?,display_type=?,is_published=?,keywords=?,details=?,details_collapsed=?,change_note=?,new_until=?,major_id=?,middle_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(sl,x.category,x.title,x.summary,x.content,x.display_type,x.is_published,x.keywords,x.details,x.details_collapsed,x.change_note,plus5(),x.major_id,x.middle_id,id).run();return J({ok:true,id,slug:sl})}
    m=u.pathname.match(/^\/api\/admin\/rules\/(\d+)\/move$/);if(m){const b=await req.json();await move(env.DB,"rules",+m[1],b.direction,"middle_id");return J({ok:true})}
    m=u.pathname.match(/^\/api\/admin\/rules\/(\d+)\/duplicate$/);if(m){const r=await env.DB.prepare("SELECT * FROM rules WHERE id=?").bind(+m[1]).first();if(!r)return J({ok:false},404);const t=`${r.title}（複製）`,sl=await unique(env.DB,"",t),n=await maxSort(env.DB,"rules",r.middle_id?"WHERE middle_id=?":"WHERE middle_id IS NULL",r.middle_id?[r.middle_id]:[]);const z=await env.DB.prepare(`INSERT INTO rules(slug,category,title,summary,content,display_type,is_published,sort_order,keywords,details,details_collapsed,new_until,major_id,middle_id,created_at,updated_at) VALUES(?,?,?,?,?,?,0,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(sl,r.category||"",t,r.summary||"",r.content||"",r.display_type||"normal",n,r.keywords||"",r.details||"",r.details_collapsed??1,plus5(),r.major_id,r.middle_id).run();return J({ok:true,id:z.meta.last_row_id})}
    m=u.pathname.match(/^\/api\/admin\/rules\/(\d+)\/retire$/);if(m){const id=+m[1],r=await env.DB.prepare("SELECT * FROM rules WHERE id=?").bind(id).first();await hist(env.DB,r,"廃止");await env.DB.prepare("UPDATE rules SET is_published=0,retired_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(id).run();return J({ok:true})}
    m=u.pathname.match(/^\/api\/admin\/rules\/(\d+)\/restore$/);if(m){await env.DB.prepare("UPDATE rules SET retired_at=NULL,is_published=0,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(+m[1]).run();return J({ok:true})}
    m=u.pathname.match(/^\/api\/admin\/rules\/(\d+)\/hard-delete$/);if(m&&req.method==="DELETE"){const id=+m[1],r=await env.DB.prepare("SELECT * FROM rules WHERE id=?").bind(id).first();if(!r?.retired_at)return J({ok:false,message:"Only retired rules"},400);await env.DB.batch([env.DB.prepare("DELETE FROM rule_history WHERE rule_id=?").bind(id),env.DB.prepare("DELETE FROM rules WHERE id=?").bind(id)]);return J({ok:true})}
    m=u.pathname.match(/^\/api\/admin\/history\/(\d+)$/);if(m){const r=await env.DB.prepare("SELECT * FROM rule_history WHERE rule_id=? ORDER BY id DESC LIMIT 50").bind(+m[1]).all();return J({ok:true,history:r.results||[]})}
    return J({ok:false,message:"Not found"},404)
  }
  return env.ASSETS.fetch(req)
}}