function json(data,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:{'content-type':'application/json; charset=UTF-8','cache-control':'no-store'}})}
function isAdmin(req,env){const t=req.headers.get('x-admin-token');return Boolean(env.ADMIN_TOKEN&&t&&t===env.ADMIN_TOKEN)}
const str=v=>String(v??'');
async function columns(db,table){const r=await db.prepare(`PRAGMA table_info(${table})`).all();return new Set((r.results||[]).map(x=>x.name))}
async function ensureSchema(db){const c=await columns(db,'rules');for(const [n,d] of [['keywords',"TEXT DEFAULT ''"],['details',"TEXT DEFAULT ''"],['details_collapsed','INTEGER DEFAULT 1'],['change_note',"TEXT DEFAULT ''"],['new_until','TEXT'],['retired_at','TEXT'],['major_id','INTEGER'],['middle_id','INTEGER']]){if(!c.has(n))await db.prepare(`ALTER TABLE rules ADD COLUMN ${n} ${d}`).run()}await db.prepare(`CREATE TABLE IF NOT EXISTS rule_major_titles(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,sort_order INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`).run();await db.prepare(`CREATE TABLE IF NOT EXISTS rule_middle_titles(id INTEGER PRIMARY KEY AUTOINCREMENT,major_id INTEGER NOT NULL,title TEXT NOT NULL,sort_order INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`).run();await db.prepare(`CREATE TABLE IF NOT EXISTS rule_history(id INTEGER PRIMARY KEY AUTOINCREMENT,rule_id INTEGER NOT NULL,title TEXT,category TEXT,summary TEXT,content TEXT,details TEXT,display_type TEXT,is_published INTEGER,change_note TEXT,saved_at TEXT DEFAULT CURRENT_TIMESTAMP)`).run()}
function plus5(){const d=new Date();d.setUTCDate(d.getUTCDate()+5);return d.toISOString()}
async function nextSort(db,table,where='',binds=[]){const r=await db.prepare(`SELECT COALESCE(MAX(sort_order),-1)+1 AS n FROM ${table} ${where}`).bind(...binds).first();return Number(r?.n||0)}
async function saveHistory(db,r,note=''){if(!r)return;await db.prepare(`INSERT INTO rule_history(rule_id,title,category,summary,content,details,display_type,is_published,change_note) VALUES(?,?,?,?,?,?,?,?,?)`).bind(r.id,r.title||'',r.category||'',r.summary||'',r.content||'',r.details||'',r.display_type||'normal',r.is_published??1,note).run()}
function slugify(t){return str(t).normalize('NFKC').toLowerCase().replace(/[^\p{Letter}\p{Number}]+/gu,'-').replace(/^-+|-+$/g,'').slice(0,80)||`rule-${Date.now()}`}
async function uniqueSlug(db,requested,title,except=null){const base=str(requested).trim()||slugify(title);let c=base,n=2;while(true){const f=except?await db.prepare('SELECT id FROM rules WHERE slug=? AND id!=? LIMIT 1').bind(c,except).first():await db.prepare('SELECT id FROM rules WHERE slug=? LIMIT 1').bind(c).first();if(!f)return c;c=`${base}-${n++}`}}
function normalize(b){const title=str(b.title).trim(),content=str(b.content).trim();if(!title||!content)return null;return{title,content,category:str(b.category).trim(),summary:str(b.summary).trim(),details:str(b.details).trim(),details_collapsed:b.details_collapsed?1:0,keywords:str(b.keywords).trim(),display_type:['normal','note','caution','important','prohibited'].includes(b.display_type)?b.display_type:'normal',is_published:b.is_published?1:0,change_note:str(b.change_note).trim(),major_id:b.major_id?Number(b.major_id):null,middle_id:b.middle_id?Number(b.middle_id):null}}
async function neighbor(db,table,row,dir,scope=null){const op=dir==='up'?'<':'>',ord=dir==='up'?'DESC':'ASC';let q=`SELECT * FROM ${table} WHERE sort_order ${op} ?`,binds=[row.sort_order];if(scope){if(row[scope]==null)q+=` AND ${scope} IS NULL`;else{q+=` AND ${scope}=?`;binds.push(row[scope])}}q+=` ORDER BY sort_order ${ord},id ${ord} LIMIT 1`;return db.prepare(q).bind(...binds).first()}
async function move(db,table,id,dir,scope=null){const r=await db.prepare(`SELECT * FROM ${table} WHERE id=?`).bind(id).first();if(!r)return;const o=await neighbor(db,table,r,dir,scope);if(!o)return;await db.batch([db.prepare(`UPDATE ${table} SET sort_order=? WHERE id=?`).bind(o.sort_order,r.id),db.prepare(`UPDATE ${table} SET sort_order=? WHERE id=?`).bind(r.sort_order,o.id)])}
export default{async fetch(req,env){const u=new URL(req.url);
if(u.pathname==='/api/rules'&&req.method==='GET'){try{await ensureSchema(env.DB);const r=await env.DB.prepare(`SELECT r.id,r.slug,r.category,r.title,r.summary,r.content,r.details,r.details_collapsed,r.keywords,r.display_type,r.sort_order,r.new_until,r.major_id,r.middle_id,ma.title major_title,ma.sort_order major_sort,mi.title middle_title,mi.sort_order middle_sort FROM rules r LEFT JOIN rule_major_titles ma ON ma.id=r.major_id LEFT JOIN rule_middle_titles mi ON mi.id=r.middle_id WHERE r.is_published=1 AND r.retired_at IS NULL ORDER BY COALESCE(ma.sort_order,999999),COALESCE(mi.sort_order,999999),r.sort_order,r.id`).all();return json({ok:true,rules:r.results||[]})}catch(e){return json({ok:false,rules:[],error:str(e?.message||e)},500)}}
if(u.pathname==='/api/admin/check'){if(!isAdmin(req,env))return json({ok:false,message:'Unauthorized'},401);await ensureSchema(env.DB);return json({ok:true})}
if(u.pathname.startsWith('/api/admin/')){if(!isAdmin(req,env))return json({ok:false,message:'Unauthorized'},401);await ensureSchema(env.DB);
if(u.pathname==='/api/admin/majors'&&req.method==='GET'){const r=await env.DB.prepare('SELECT * FROM rule_major_titles ORDER BY sort_order,id').all();return json({ok:true,majors:r.results||[]})}
if(u.pathname==='/api/admin/majors'&&req.method==='POST'){const b=await req.json().catch(()=>({})),title=str(b.title).trim();if(!title)return json({ok:false},400);const sort=await nextSort(env.DB,'rule_major_titles'),r=await env.DB.prepare('INSERT INTO rule_major_titles(title,sort_order) VALUES(?,?)').bind(title,sort).run();return json({ok:true,id:r.meta?.last_row_id},201)}
let m=u.pathname.match(/^\/api\/admin\/majors\/(\d+)$/);if(m&&req.method==='PUT'){const b=await req.json().catch(()=>({})),title=str(b.title).trim();if(!title)return json({ok:false},400);await env.DB.prepare('UPDATE rule_major_titles SET title=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(title,+m[1]).run();return json({ok:true})}
m=u.pathname.match(/^\/api\/admin\/majors\/(\d+)\/move$/);if(m&&req.method==='POST'){const b=await req.json().catch(()=>({}));await move(env.DB,'rule_major_titles',+m[1],b.direction);return json({ok:true})}
if(u.pathname==='/api/admin/middles'&&req.method==='GET'){const r=await env.DB.prepare('SELECT mi.*,ma.title major_title FROM rule_middle_titles mi LEFT JOIN rule_major_titles ma ON ma.id=mi.major_id ORDER BY COALESCE(ma.sort_order,999999),mi.sort_order,mi.id').all();return json({ok:true,middles:r.results||[]})}
if(u.pathname==='/api/admin/middles'&&req.method==='POST'){const b=await req.json().catch(()=>({})),title=str(b.title).trim(),major=+b.major_id;if(!title||!major)return json({ok:false},400);const sort=await nextSort(env.DB,'rule_middle_titles','WHERE major_id=?',[major]),r=await env.DB.prepare('INSERT INTO rule_middle_titles(major_id,title,sort_order) VALUES(?,?,?)').bind(major,title,sort).run();return json({ok:true,id:r.meta?.last_row_id},201)}
m=u.pathname.match(/^\/api\/admin\/middles\/(\d+)$/);if(m&&req.method==='PUT'){const b=await req.json().catch(()=>({})),title=str(b.title).trim(),major=+b.major_id;if(!title||!major)return json({ok:false},400);await env.DB.prepare('UPDATE rule_middle_titles SET title=?,major_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(title,major,+m[1]).run();return json({ok:true})}
m=u.pathname.match(/^\/api\/admin\/middles\/(\d+)\/move$/);if(m&&req.method==='POST'){const b=await req.json().catch(()=>({}));await move(env.DB,'rule_middle_titles',+m[1],b.direction,'major_id');return json({ok:true})}
if(u.pathname==='/api/admin/rules'&&req.method==='GET'){const r=await env.DB.prepare(`SELECT r.*,ma.title major_title,mi.title middle_title FROM rules r LEFT JOIN rule_major_titles ma ON ma.id=r.major_id LEFT JOIN rule_middle_titles mi ON mi.id=r.middle_id ORDER BY CASE WHEN r.retired_at IS NULL THEN 0 ELSE 1 END,COALESCE(ma.sort_order,999999),COALESCE(mi.sort_order,999999),r.sort_order,r.id`).all();return json({ok:true,rules:r.results||[]})}
if(u.pathname==='/api/admin/rules'&&req.method==='POST'){const b=await req.json().catch(()=>({})),x=normalize(b);if(!x)return json({ok:false},400);const slug=await uniqueSlug(env.DB,b.slug,x.title),sort=await nextSort(env.DB,'rules',x.middle_id?'WHERE middle_id=?':'WHERE middle_id IS NULL',x.middle_id?[x.middle_id]:[]);const r=await env.DB.prepare(`INSERT INTO rules(slug,category,title,summary,content,display_type,is_published,sort_order,keywords,details,details_collapsed,change_note,new_until,major_id,middle_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(slug,x.category,x.title,x.summary,x.content,x.display_type,x.is_published,sort,x.keywords,x.details,x.details_collapsed,x.change_note,plus5(),x.major_id,x.middle_id).run();return json({ok:true,id:r.meta?.last_row_id,slug},201)}
m=u.pathname.match(/^\/api\/admin\/rules\/(\d+)$/);if(m&&req.method==='PUT'){const id=+m[1],old=await env.DB.prepare('SELECT * FROM rules WHERE id=?').bind(id).first(),b=await req.json().catch(()=>({})),x=normalize(b);if(!old||!x)return json({ok:false},400);await saveHistory(env.DB,old,x.change_note);const slug=await uniqueSlug(env.DB,b.slug||old.slug,x.title,id);await env.DB.prepare(`UPDATE rules SET slug=?,category=?,title=?,summary=?,content=?,display_type=?,is_published=?,keywords=?,details=?,details_collapsed=?,change_note=?,new_until=?,major_id=?,middle_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(slug,x.category,x.title,x.summary,x.content,x.display_type,x.is_published,x.keywords,x.details,x.details_collapsed,x.change_note,plus5(),x.major_id,x.middle_id,id).run();return json({ok:true,id,slug})}
m=u.pathname.match(/^\/api\/admin\/rules\/(\d+)\/move$/);if(m&&req.method==='POST'){const b=await req.json().catch(()=>({}));await move(env.DB,'rules',+m[1],b.direction,'middle_id');return json({ok:true})}
m=u.pathname.match(/^\/api\/admin\/rules\/(\d+)\/duplicate$/);if(m&&req.method==='POST'){const r=await env.DB.prepare('SELECT * FROM rules WHERE id=?').bind(+m[1]).first();if(!r)return json({ok:false},404);const title=`${r.title}（複製）`,slug=await uniqueSlug(env.DB,'',title),sort=await nextSort(env.DB,'rules',r.middle_id?'WHERE middle_id=?':'WHERE middle_id IS NULL',r.middle_id?[r.middle_id]:[]),z=await env.DB.prepare(`INSERT INTO rules(slug,category,title,summary,content,display_type,is_published,sort_order,keywords,details,details_collapsed,new_until,major_id,middle_id,created_at,updated_at) VALUES(?,?,?,?,?,?,0,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(slug,r.category||'',title,r.summary||'',r.content||'',r.display_type||'normal',sort,r.keywords||'',r.details||'',r.details_collapsed??1,plus5(),r.major_id,r.middle_id).run();return json({ok:true,id:z.meta?.last_row_id},201)}
m=u.pathname.match(/^\/api\/admin\/rules\/(\d+)\/retire$/);if(m&&req.method==='POST'){const id=+m[1],r=await env.DB.prepare('SELECT * FROM rules WHERE id=?').bind(id).first();if(!r)return json({ok:false},404);await saveHistory(env.DB,r,'廃止');await env.DB.prepare('UPDATE rules SET is_published=0,retired_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(id).run();return json({ok:true})}
m=u.pathname.match(/^\/api\/admin\/rules\/(\d+)\/restore$/);if(m&&req.method==='POST'){await env.DB.prepare('UPDATE rules SET retired_at=NULL,is_published=0,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(+m[1]).run();return json({ok:true})}
m=u.pathname.match(/^\/api\/admin\/rules\/(\d+)\/hard-delete$/);if(m&&req.method==='DELETE'){const id=+m[1],r=await env.DB.prepare('SELECT * FROM rules WHERE id=?').bind(id).first();if(!r?.retired_at)return json({ok:false},400);await env.DB.batch([env.DB.prepare('DELETE FROM rule_history WHERE rule_id=?').bind(id),env.DB.prepare('DELETE FROM rules WHERE id=?').bind(id)]);return json({ok:true})}
m=u.pathname.match(/^\/api\/admin\/history\/(\d+)$/);if(m&&req.method==='GET'){const r=await env.DB.prepare('SELECT * FROM rule_history WHERE rule_id=? ORDER BY id DESC LIMIT 50').bind(+m[1]).all();return json({ok:true,history:r.results||[]})}
return json({ok:false,message:'Not found'},404)}
return env.ASSETS.fetch(req)}}
