function json(data,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:{'content-type':'application/json; charset=UTF-8','cache-control':'no-store'}})}
const clean=(v,n=100000)=>String(v??'').slice(0,n);
const admin=(r,e)=>Boolean(e.ADMIN_TOKEN&&r.headers.get('x-admin-token')===e.ADMIN_TOKEN);
const unauth=()=>json({ok:false,message:'Unauthorized'},401);
function slugify(s){return clean(s,100).normalize('NFKC').toLowerCase().replace(/[^\p{Letter}\p{Number}]+/gu,'-').replace(/^-+|-+$/g,'').slice(0,80)||`rule-${Date.now()}`}
async function ensure(db){
 const info=await db.prepare('PRAGMA table_info(rules)').all(), cols=new Set((info.results||[]).map(x=>x.name));
 for(const [n,d] of [['keywords',"TEXT DEFAULT ''"],['details',"TEXT DEFAULT ''"],['details_collapsed','INTEGER DEFAULT 1'],['change_note',"TEXT DEFAULT ''"],['new_until','TEXT DEFAULT NULL'],['retired_at','TEXT DEFAULT NULL'],['major_category',"TEXT DEFAULT ''"],['sub_category',"TEXT DEFAULT ''"]]) if(!cols.has(n)) await db.prepare(`ALTER TABLE rules ADD COLUMN ${n} ${d}`).run();
 await db.prepare(`CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY AUTOINCREMENT,parent_id INTEGER,title TEXT NOT NULL,icon TEXT DEFAULT '📘',sort_order INTEGER DEFAULT 0,is_published INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`).run();
 await db.prepare(`CREATE TABLE IF NOT EXISTS rule_history(id INTEGER PRIMARY KEY AUTOINCREMENT,rule_id INTEGER NOT NULL,title TEXT NOT NULL,category TEXT NOT NULL,major_category TEXT DEFAULT '',sub_category TEXT DEFAULT '',content TEXT NOT NULL,details TEXT DEFAULT '',display_type TEXT DEFAULT 'normal',is_published INTEGER DEFAULT 1,change_note TEXT DEFAULT '',saved_at TEXT DEFAULT CURRENT_TIMESTAMP)`).run();
 await db.prepare(`CREATE TABLE IF NOT EXISTS updates(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT NOT NULL DEFAULT 'rule',title TEXT NOT NULL,description TEXT DEFAULT '',rule_id INTEGER,rule_slug TEXT,category TEXT DEFAULT '',old_content TEXT DEFAULT '',new_content TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP)`).run();
 const ui=await db.prepare('PRAGMA table_info(updates)').all(), uc=new Set((ui.results||[]).map(x=>x.name));
 for(const [n,d] of [['category',"TEXT DEFAULT ''"],['old_content',"TEXT DEFAULT ''"],['new_content',"TEXT DEFAULT ''"]]) if(!uc.has(n)) await db.prepare(`ALTER TABLE updates ADD COLUMN ${n} ${d}`).run();
}
async function uniqueSlug(db,s,title,except){let base=slugify(s||title),c=base,n=2;while(true){let f=except?await db.prepare('SELECT id FROM rules WHERE slug=? AND id!=?').bind(c,except).first():await db.prepare('SELECT id FROM rules WHERE slug=?').bind(c).first();if(!f)return c;c=`${base}-${n++}`}}
async function history(db,r,note=''){if(!r)return;await db.prepare(`INSERT INTO rule_history(rule_id,title,category,major_category,sub_category,content,details,display_type,is_published,change_note) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(r.id,r.title,r.category||'',r.major_category||r.category||'',r.sub_category||'',r.content,r.details||'',r.display_type||'normal',r.is_published??1,note).run()}
async function updateLog(db,o){await db.prepare(`INSERT INTO updates(type,title,description,rule_id,rule_slug,category,old_content,new_content) VALUES(?,?,?,?,?,?,?,?)`).bind(o.type||'rule',o.title,o.description||'',o.ruleId||null,o.ruleSlug||null,o.category||'',o.oldContent||'',o.newContent||'').run()}
function norm(b){let title=clean(b.title,200).trim(),major=clean(b.major_category||b.category,100).trim(),sub=clean(b.sub_category,100).trim(),content=clean(b.content).trim();if(!title||!major||!content)return{error:'大タイトル・ルール名・本文は必須です'};let types=new Set(['normal','note','caution','important','prohibited']);return{value:{title,major,sub,content,details:clean(b.details).trim(),details_collapsed:b.details_collapsed?1:0,keywords:clean(b.keywords,1000).trim(),display_type:types.has(b.display_type)?b.display_type:'normal',is_published:b.is_published?1:0,sort_order:Number(b.sort_order)||0,change_note:clean(b.change_note,1000).trim()}}}
export default {async fetch(request,env){const u=new URL(request.url);if(u.pathname.startsWith('/api/'))await ensure(env.DB);
 if(u.pathname==='/api/health')return json({ok:Boolean(await env.DB.prepare('SELECT 1 ok').first())});
 if(u.pathname==='/api/categories'&&request.method==='GET'){let x=await env.DB.prepare(`SELECT * FROM categories WHERE is_published=1 ORDER BY parent_id IS NOT NULL,parent_id,sort_order,id`).all();return json({ok:true,categories:x.results||[]})}
 if(u.pathname==='/api/rules'&&request.method==='GET'){let x=await env.DB.prepare(`SELECT id,slug,COALESCE(NULLIF(major_category,''),category) major_category,sub_category,title,content,details,details_collapsed,keywords,display_type,sort_order,new_until,updated_at FROM rules WHERE is_published=1 AND retired_at IS NULL ORDER BY sort_order,id`).all();return json({ok:true,rules:x.results||[]})}
 if(u.pathname==='/api/updates'&&request.method==='GET'){let x=await env.DB.prepare(`SELECT * FROM updates ORDER BY id DESC LIMIT 200`).all();return json({ok:true,updates:x.results||[]})}
 if(u.pathname==='/api/admin/check'){if(!admin(request,env))return unauth();return json({ok:true})}
 if(u.pathname.startsWith('/api/admin/')){if(!admin(request,env))return unauth();
  if(u.pathname==='/api/admin/rules'&&request.method==='GET'){let x=await env.DB.prepare(`SELECT *,COALESCE(NULLIF(major_category,''),category) major_category FROM rules ORDER BY sort_order,id`).all();return json({ok:true,rules:x.results||[]})}
  if(u.pathname==='/api/admin/categories'&&request.method==='GET'){let x=await env.DB.prepare(`SELECT * FROM categories ORDER BY parent_id IS NOT NULL,parent_id,sort_order,id`).all();return json({ok:true,categories:x.results||[]})}
  if(u.pathname==='/api/admin/categories'&&request.method==='POST'){let b=await request.json(),title=clean(b.title,100).trim();if(!title)return json({ok:false,message:'名前が必要です'},400);let r=await env.DB.prepare(`INSERT INTO categories(parent_id,title,icon,sort_order,is_published) VALUES(?,?,?,?,?)`).bind(b.parent_id||null,title,clean(b.icon,8)||'📘',Number(b.sort_order)||0,b.is_published===false?0:1).run();return json({ok:true,id:r.meta?.last_row_id},201)}
  let cm=u.pathname.match(/^\/api\/admin\/categories\/(\d+)$/);if(cm&&request.method==='PUT'){let b=await request.json();await env.DB.prepare(`UPDATE categories SET title=?,icon=?,sort_order=?,is_published=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(clean(b.title,100).trim(),clean(b.icon,8)||'📘',Number(b.sort_order)||0,b.is_published===false?0:1,+cm[1]).run();return json({ok:true})}
  if(u.pathname==='/api/admin/reorder'&&request.method==='POST'){let b=await request.json(),table=b.kind==='category'?'categories':'rules',ids=Array.isArray(b.ids)?b.ids:[];for(let i=0;i<ids.length;i++)await env.DB.prepare(`UPDATE ${table} SET sort_order=? WHERE id=?`).bind(i,+ids[i]).run();return json({ok:true})}
  if(u.pathname==='/api/admin/rules'&&request.method==='POST'){let b=await request.json(),n=norm(b);if(n.error)return json({ok:false,message:n.error},400);let r=n.value,s=await uniqueSlug(env.DB,b.slug,r.title);let q=await env.DB.prepare(`INSERT INTO rules(slug,category,major_category,sub_category,title,summary,content,display_type,is_published,sort_order,keywords,details,details_collapsed,change_note,new_until,created_at,updated_at) VALUES(?,?,?,?,?,'',?,?,?,?,?,?,?,?,datetime('now','+5 days'),CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(s,r.major,r.major,r.sub,r.title,r.content,r.display_type,r.is_published,r.sort_order,r.keywords,r.details,r.details_collapsed,r.change_note).run();let id=q.meta?.last_row_id;await updateLog(env.DB,{title:`新規ルール：${r.title}`,description:r.change_note||'新しいルールを追加しました。',ruleId:id,ruleSlug:s,category:r.major,newContent:r.content});return json({ok:true,id,slug:s},201)}
  let rm=u.pathname.match(/^\/api\/admin\/rules\/(\d+)$/);if(rm&&request.method==='PUT'){let id=+rm[1],old=await env.DB.prepare('SELECT * FROM rules WHERE id=?').bind(id).first();if(!old)return json({ok:false,message:'Rule not found'},404);let b=await request.json(),n=norm(b);if(n.error)return json({ok:false,message:n.error},400);let r=n.value,s=await uniqueSlug(env.DB,b.slug||old.slug,r.title,id);let changed=old.title!==r.title||(old.major_category||old.category)!==r.major||old.sub_category!==r.sub||old.content!==r.content||(old.details||'')!==r.details||old.display_type!==r.display_type;if(changed)await history(env.DB,old,r.change_note);await env.DB.prepare(`UPDATE rules SET slug=?,category=?,major_category=?,sub_category=?,title=?,summary='',content=?,display_type=?,is_published=?,sort_order=?,keywords=?,details=?,details_collapsed=?,change_note=?,new_until=CASE WHEN ? THEN datetime('now','+5 days') ELSE new_until END,retired_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(s,r.major,r.major,r.sub,r.title,r.content,r.display_type,r.is_published,r.sort_order,r.keywords,r.details,r.details_collapsed,r.change_note,changed?1:0,id).run();if(changed||r.change_note)await updateLog(env.DB,{title:`ルール更新：${r.title}`,description:r.change_note||'内容を更新しました。',ruleId:id,ruleSlug:s,category:r.major,oldContent:old.content,newContent:r.content});return json({ok:true,id,slug:s})}
  if(rm&&request.method==='DELETE'){let id=+rm[1],old=await env.DB.prepare('SELECT * FROM rules WHERE id=?').bind(id).first();if(!old)return json({ok:false},404);await history(env.DB,old,'廃止');await env.DB.prepare(`UPDATE rules SET is_published=0,retired_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(id).run();await updateLog(env.DB,{title:`ルール廃止：${old.title}`,description:'このルールは廃止されました。',ruleId:id,ruleSlug:old.slug,category:old.major_category||old.category,oldContent:old.content});return json({ok:true})}
  if(u.pathname==='/api/admin/duplicate'&&request.method==='POST'){let b=await request.json(),old=await env.DB.prepare('SELECT * FROM rules WHERE id=?').bind(+b.id).first();if(!old)return json({ok:false},404);let s=await uniqueSlug(env.DB,'',`${old.title}-コピー`);let q=await env.DB.prepare(`INSERT INTO rules(slug,category,major_category,sub_category,title,summary,content,display_type,is_published,sort_order,keywords,details,details_collapsed,change_note,created_at,updated_at) VALUES(?,?,?,?,?,'',?,?,0,?,?,?,?,?,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(s,old.category,old.major_category||old.category,old.sub_category||'',`${old.title}（コピー）`,old.content,old.display_type,old.sort_order+1,old.keywords||'',old.details||'',old.details_collapsed??1).run();return json({ok:true,id:q.meta?.last_row_id})}
  let hm=u.pathname.match(/^\/api\/admin\/history\/(\d+)$/);if(hm){let x=await env.DB.prepare('SELECT * FROM rule_history WHERE rule_id=? ORDER BY id DESC LIMIT 50').bind(+hm[1]).all();return json({ok:true,history:x.results||[]})}
  return json({ok:false,message:'Not found'},404)
 }
 return env.ASSETS.fetch(request)}};
